version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: examples/
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: tests/
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
