version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: examples/
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: tests/
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - '*'

    ignore:
      # XXX: Update rollup major version.
      # Rollup v4 requires node 18. Chromium uses node 16 (https://crbug.com/1408209).
      # https://github.com/GoogleChromeLabs/chromium-bidi/pull/1438#issuecomment-1764534973
      - dependency-name: rollup
        versions: ['>=4.0.0']
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
      - dependency-name: devtools-protocol
      - dependency-name: chai
        versions: ['>=5.0.0']
        update-types: ['version-update:semver-major']
