name: Chromium roll reminder

# Declare default permissions as read only.
permissions: read-all

on:
  pull_request:
    types: [labeled]

jobs:
  post-message:
    name: Post Chromium roll reminder
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains(github.event.label.name, 'autorelease') && contains(github.event.label.name, 'tagged')
    steps:
      - name: Find Comment Id
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2.4.0
        id: find-comment-id
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
      - name: Upsert comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
        with:
          comment-id: ${{ steps.find-comment-id.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            Please create a Chromium CL to roll latest version of Mapper.
            Follow the instructions in [Roll into Chromium](https://github.com/GoogleChromeLabs/chromium-bidi#roll-into-chromium).
