name: Chromium roll reminder

# Declare default permissions as read only.
permissions: read-all

on:
  pull_request:
    types: [labeled]

jobs:
  post-message:
    name: Post Chromium roll reminder
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains(github.event.label.name, 'autorelease') && contains(github.event.label.name, 'tagged')
    steps:
      - name: Find Comment Id
        uses: peter-evans/find-comment@d5fe37641ad8451bdd80312415672ba26c86575e # v3.0.0
        id: find-comment-id
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
      - name: Upsert comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          comment-id: ${{ steps.find-comment-id.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            Please create a Chromium CL to roll latest version of Mapper.
            Follow the instructions in [Roll into Chromium](https://github.com/GoogleChromeLabs/chromium-bidi#roll-into-chromium).
