# This workflow will update the version in .browser and open a PR

name: 'Creates a release PR'

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Release bumping type
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          cache: npm
      - name: Install npm dependencies (skip build)
        run: npm ci --ignore-scripts
      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.type }} -m 'Release v%s' --no-git-tag-version
      - name: Get release version
        id: version
        run: |
          PACKAGE_VERSION=$(cat package.json | jq -r '.version')
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/release
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          title: 'Release ${{steps.version.outputs.version}}'
          body: 'Automatically generated by https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/create-release-pr.yml'
