# This workflow will run headful and headless E2E tests.

name: E2E tests

on:
  pull_request:
  push:
    branches: 'main'

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        head: [headful, headless]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: Install and build npm dependencies
        run: npm ci
      - name: Install Chromium
        run: |
          # browsers from @puppeteer/browsers
          echo "chromium_binary=$(npx browsers install chromium@latest | cut -f 2 -d' ')" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt
      - name: Run E2E tests
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.head == 'headful' }}
        timeout-minutes: 15
        run: CHROME_BIN="${{ env.chromium_binary }}" xvfb-run --auto-servernum npm run e2e-${{ matrix.head }}
      - name: Run E2E tests
        if: ${{ matrix.os == 'macos-latest' || (matrix.os == 'ubuntu-latest' && matrix.head == 'headless') }}
        timeout-minutes: 15
        run: CHROME_BIN="${{ env.chromium_binary }}" npm run e2e-${{ matrix.head }}

env:
  DEBUG: bidiServer:log
  FORCE_COLOR: 3
