# This workflow will run headful and headless E2E tests.

name: E2E tests

on:
  pull_request:
  push:
    branches: 'main'
  workflow_dispatch:
    inputs:
      verbose:
        description: Verbose logging
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        head: [headful, headless]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: Install and build npm dependencies
        run: npm ci
      - name: Setup cache for browser binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/chromium-bidi
          key: ${{ runner.os }}-browsers-${{ hashFiles('.browser') }}) }}
      - name: Install pinned browser
        id: browser
        run: node install-browser.mjs ~/.cache/chromium-bidi
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt
      - name: Run E2E tests
        if: matrix.os == 'ubuntu-latest' && matrix.head == 'headful'
        timeout-minutes: 20
        run: >
          xvfb-run --auto-servernum
          npm run e2e-${{ matrix.head }}
        # For verbose logging, set `DEBUG: 'bidiMapper:mapperDebug:*'` and `VERBOSE: true`.
        env:
          BROWSER_BIN: ${{ steps.browser.outputs.executablePath }}
          VERBOSE: ${{ github.event.inputs.verbose }}
      - name: Run E2E tests
        if: matrix.os == 'macos-latest' || (matrix.os == 'ubuntu-latest' && matrix.head == 'headless')
        timeout-minutes: 20
        run: npm run e2e-${{ matrix.head }}
        # For verbose logging, set `DEBUG: 'bidiMapper:mapperDebug:*'` and `VERBOSE: true`.
        env:
          BROWSER_BIN: ${{ steps.browser.outputs.executablePath }}
          VERBOSE: ${{ github.event.inputs.verbose }}
      - name: Upload artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.head }}-artifacts
          path: logs

env:
  DEBUG: 'bidiServer:log,bidiMapper:mapperDebug:*'
  FORCE_COLOR: 3
  PIP_DISABLE_PIP_VERSION_CHECK: 1
