# This workflow will run headful and headless E2E tests.

name: E2E tests

on:
  pull_request:
  push:
    branches: 'main'

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04] # macos-latest
        head: [
            headless,
            headless,
            headless,
            headless,
            headless,
            headless,
            headless,
            headless,
            headless,
            headless,
          ] # headful
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: Install and build npm dependencies
        run: npm ci
      - name: Install Chrome
        run: echo "chrome_binary=$(npx @puppeteer/browsers install chrome@latest | cut -f 2- -d' ')" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt
      - name: Run E2E tests
        timeout-minutes: 20
        run: npm run e2e-${{ matrix.head }}
        env:
          BROWSER_BIN: ${{ env.chrome_binary }}
          DEBUG: '*'
          VERBOSE: true
      - name: Upload artifacts
        # Force run task even if the previous tasks failed.
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.head }}-artifacts
          path: logs

env:
  DEBUG: bidiServer:log
  FORCE_COLOR: 3
  PIP_DISABLE_PIP_VERSION_CHECK: 1
