# This workflow will check out wpt and run the WebDriver BiDi tests against our
# implementation.

name: Generate WPT report

on:
  push:
    branches: 'main'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  wpt:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install and build npm dependencies
        run: npm ci
      - name: Setup dirs
        run: mkdir -p out
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Set up virtualenv
        run: pip install virtualenv
      - name: Set up hosts
        run: ./wpt make-hosts-file | sudo tee -a /etc/hosts
        working-directory: wpt
      - name: Install Chromium
        run: echo "chromium_binary=$(npx @puppeteer/browsers install chromium@latest | cut -f 2- -d' ')" >> $GITHUB_ENV
      - name: Run WPT tests
        timeout-minutes: 60
        run: ./runWPT.sh webdriver/tests/bidi/
        env:
          BROWSER_BIN: ${{ env.chromium_binary }}
          CHROMEDRIVER: true
          WPT_REPORT: out/wptreport.json
      - name: Generate HTML test report
        # Force run task even if the previous tasks failed.
        if: ${{ always() }}
        run: >
          node test-report/htmlWptReport.mjs
          out/wptreport.json
          out/wptreport.html
      - name: Upload artifacts
        # Force run task even if the previous tasks failed.
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: wpt-chromedriver-artifacts
          path: out
      # The following steps should be done only for merges in `main`.
      - name: Prepare Pages
        if: ${{ always() }}
        run: mkdir -p out/site; cp out/wptreport.html out/site/index.html
      - name: Setup Pages
        if: ${{ always() }}
        uses: actions/configure-pages@v3
      - name: Upload Pages artifact
        if: ${{ always() }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: out/site
      - name: Deploy to GitHub Pages
        if: ${{ always() }}
        id: deployment
        uses: actions/deploy-pages@v2

env:
  DEBUG: bidiServer:log
  FORCE_COLOR: 3
  PIP_DISABLE_PIP_VERSION_CHECK: 1
