# https://github.com/pre-commit/action

name: Pre-commit

# Declare default permissions as read only.
permissions: read-all

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

on:
  merge_group:
  pull_request:
  push:
    branches: 'main'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5.3
      - name: Set up Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          cache: npm
      - uses: google/wireit@f3a3c79c553122e2fe5829eeac7d815326502903 # setup-github-actions-caching/v1
      - run: npm ci
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11'
          cache: pip
      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 #v3.0.0
        with:
          # We need --all-files as this overrides the defaults
          extra_args: --hook-stage manual --all-files
