# https://github.com/pre-commit/action

name: Pre-commit

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

on:
  merge_group:
  pull_request:
  push:
    branches: 'main'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v1
      - run: npm ci
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - uses: pre-commit/action@v3.0.0
