name: Publish

on:
  push:
    tags:
      - '*v*'

env:
  FORCE_COLOR: 3
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      - name: Set up Node.js
        uses: actions/setup-node@698d50532ea4cc0490274810a45fe52318110a1c
        with:
          node-version: 16
          cache: npm
      - name: Set up Python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Node dependencies
        run: npm ci
      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt
      - name: Test
        run: npm run unit
      - name: Publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm config set registry 'https://wombat-dressing-room.appspot.com/'
          npm config set '//wombat-dressing-room.appspot.com/:_authToken' '${NPM_TOKEN}'
          npm publish
