name: Puppeteer CI

# Declare default permissions as read only.
permissions: read-all

on:
  pull_request:
    types:
      # These are the defaults. See
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - synchronize

      # Used for `puppeteer`
      - labeled
  workflow_dispatch:

concurrency:
  group: puppeteer-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  puppeteer-test:
    name: Run Puppeteer tests
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'puppeteer')
    steps:
      - name: Checkout Chromium-BiDi
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: 'bidi'
      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@36c6454b5a2348e7794ba2d82a21506605921e3d # v3.0.0
      - name: Set up Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version-file: './bidi/.nvmrc'
      - name: Install Chromium-BiDi dependencies
        working-directory: bidi
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      - name: Build Chromium-BiDi
        working-directory: bidi
        run: |
          npm run build
      - name: Link Chromium-BiDi
        working-directory: bidi
        run: npm link

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: 'puppeteer/puppeteer'
          path: 'puppeteer'
      - name: Install Puppeteer dependencies
        working-directory: puppeteer
        run: npm ci
      # We need to build Puppeteer first to not hit devtools protocol dep issue
      - name: Build Puppeteer
        working-directory: puppeteer
        run: npm run build
      - name: Install Chromium-BiDi
        working-directory: puppeteer
        run: |
          npm link chromium-bidi -w puppeteer-core
      - name: Setup cache for browser binaries
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: ~/.cache/chromium-bidi
          key: ${{ runner.os }}-browsers-${{ hashFiles('.browser') }}) }}
      - name: Install pinned browser
        id: browser
        working-directory: bidi
        run: node tools/install-browser.mjs --github
      - name: Run tests
        working-directory: puppeteer
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.browser.outputs.executablePath }}
        run: xvfb-run --auto-servernum npm run test:chrome:bidi
