name: Creates a release PR

on:
  push:
    branches: 'main'
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Release bumping type
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  create-release-pr:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          cache: npm
      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.type }} -m 'Release v%s' --no-git-tag-version
      - name: Get release version
        id: version
        run: echo "version=$(jq -r '.version' < package.json)" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/release
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          title: 'Release ${{steps.version.outputs.version}}'
          commit-message: 'Release ${{steps.version.outputs.version}}'
          body: 'Automatically generated by https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/release.yml'

  release:
    if: ${{ github.event_name == 'push' && startsWith(github.event.head_commit.message, 'Release') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Get release version
        id: version
        run: echo "version=$(jq -r '.version' < package.json)" >> $GITHUB_OUTPUT
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.version.outputs.version }}
