# https://github.com/pre-commit/action

name: Release new npm version

on:
  push:
    branches: 'main'

jobs:
  release:
    if: ${{ startsWith(github.event.head_commit.message, 'Release') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Get release version
        id: version
        run: |
          PACKAGE_VERSION=$(cat package.json | jq -r '.version')
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.version.outputs.version }}
