# This workflow will update the version in .browser and open a PR

name: 'Update the pinned browser version'

# Declare default permissions as read only.
permissions: read-all

on:
  schedule:
    # Run hourly at xx:30.
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Checkout `browser-automation-bot/update-browser-version` if exits
        run: |
          (git ls-remote --exit-code --heads origin refs/heads/browser-automation-bot/update-browser-version &&
          git checkout browser-automation-bot/update-browser-version &&
          git rebase main) || exit 0
      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Update browser pin and devtools-protocol
        run: node tools/update_chrome_revision.mjs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-browser-version
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: 'build(chrome): update the pinned browser version'
          title: 'build(chrome): update the pinned browser version'
          body: 'Automatically generated by https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml'
          labels: dependencies
