# This workflow will update the WebdriverBidi types.

name: Update WebdriverBidi types

# Declare default permissions as read only.
permissions: read-all

on:
  schedule:
    # Run daily at 10AM.
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      source_ref:
        description: Ref in spec repo to update from. Default is `main`.
        default: main
        required: false
        type: string
      repository:
        description: Repository with the spec to update from. Default is `w3c/webdriver-bidi`.
        default: w3c/webdriver-bidi
        required: false
        type: string

jobs:
  build:
    name: Build WebDriverBidi types
    runs-on: ubuntu-latest
    steps:
      - name: Check out the main spec repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          repository: ${{ github.event.inputs.repository || 'w3c/webdriver-bidi' }}
          ref: ${{ github.event.inputs.source_ref || 'main' }}
          path: webdriver-bidi
      - name: Check out w3c/permissions spec repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          repository: w3c/permissions
          ref: main
          path: permissions
      - name: Generate WebDriverBidi CDDL
        run: ./scripts/test.sh
        working-directory: webdriver-bidi
      - name: Upload WebDriverBidi CDDL
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: all-cddl
          path: webdriver-bidi/all.cddl
      - name: Generate WebDriverBidi CDDL for Permissions
        run: ../webdriver-bidi/scripts/cddl/generate.js ./index.html && mv all.cddl permissions.cddl
        working-directory: permissions
      - name: Upload WebDriverBidi CDDL for Permissions
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: permissions-cddl
          path: permissions/permissions.cddl

  pr:
    name: Send PR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out mapper repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.11'
          cache: pip
      - name: Setup Go
        uses: actions/setup-go@be1aa1186e83689f3e45adaf3697af86f816fb2e # v5.0.0
        with:
          go-version: '1.21.x'
      - name: Install cddlconv
        run: cargo install cddlconv@0.1.5
      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - uses: google/wireit@4aad131006ea85c1e42af927534ebb13426dd730 # setup-github-actions-caching/v1.0.2
      - name: Install and build npm dependencies
        run: npm ci
      - name: Download WebDriverBidi CDDL
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: all-cddl
      - name: Download WebDriverBidi CDDL for Permissions
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: permissions-cddl
      - name: Generate TypeScript types for the main spec
        run: node tools/generate-bidi-types.mjs --cddl-file all.cddl
      - name: Generate TypeScript types for Permissions spec
        run: node tools/generate-bidi-types.mjs --cddl-file permissions.cddl --ts-file src/protocol/generated/webdriver-bidi-permissions.ts --zod-file src/protocol-parser/generated/webdriver-bidi-permissions.ts
      - run: git diff
      # Needed for `npm run format`.
      - run: python -m pip install pre-commit
      - run: python -m pip freeze --local
      - name: Run formatter
        run: npm run format || npm run format
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6.0.2
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-bidi-types
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: 'build(spec): update WebDriverBidi types'
          title: 'build(spec): update WebDriverBidi types'
          body: Automatically generated by https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-bidi-types.yml
          labels: dependencies
