# This workflow will update the version in .browser and open a PR

name: 'Update the pinned browser version'

# Declare default permissions as read only.
permissions: read-all

on:
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Checkout `browser-automation-bot/update-browser-version` if exits
        run: |
          (git ls-remote --exit-code --heads origin refs/heads/browser-automation-bot/update-browser-version &&
          git checkout browser-automation-bot/update-browser-version &&
          git rebase main) || exit 0
      - name: Set up Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install and build npm dependencies
        run: npm ci
      - name: Update browser pin and devtools-protocol
        id: update
        run: node tools/update_chrome_revision.mjs
      - name: Create Pull Request
        if: ${{ steps.update.outputs.commit }}
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-browser-version
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: ${{ steps.update.outputs.commit }}
          title: ${{ steps.update.outputs.commit }}
          body: 'Automatically generated by https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml'
          push-to-fork: browser-automation-bot/chromium-bidi
