# This workflow will update the WebdriverBidi types.

name: Update WebdriverBidi types

# Declare default permissions as read only.
permissions: read-all

on:
  schedule:
    # Run daily at 10AM.
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build WebDriverBidi types
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          repository: w3c/webdriver-bidi
      - name: Generate WebDriverBidi CDDL
        run: ./scripts/test.sh
      - name: Upload WebDriverBidi CDDL
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05 # v3.1.2
        with:
          name: all-cddl
          path: all.cddl
  pr:
    name: Send PR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: '3.11'
          cache: pip
      - name: Set up Rust
        run: rustup update stable && rustup default stable
      - name: Install cddlconv
        run: cargo install --git https://github.com/jrandolf/cddlconv.git cddlconv
      - name: Set up Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: 18
          cache: npm
      - uses: google/wireit@f3a3c79c553122e2fe5829eeac7d815326502903 # setup-github-actions-caching/v1
      - name: Install and build npm dependencies
        run: npm ci
      - name: Download WebDriverBidi CDDL
        uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b # v3.0.2
        with:
          name: all-cddl
      - name: Generate TypeScript types
        run: npm run bidi-types -- all.cddl
      # Needed for `npm run format`.
      - name: Install pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 #v3.0.0
      - name: Run formatter
        run: npm run format || exit 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-bidi-types
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: 'build(spec): update WebDriverBidi types'
          title: 'build(spec): update WebDriverBidi types'
          body: Automatically generated by https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-bidi-types.yml
          labels: dependencies
