# This workflow will update the WebdriverBidi types.

name: Update WebdriverBidi types

# Declare default permissions as read only.
permissions: read-all

on:
  schedule:
    # Run daily at 10AM.
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      source_ref:
        description: Ref in spec repo to update from. Default is `main`.
        default: main
        required: false
        type: string
      repository:
        description: Repository with the spec to update from. Default is `w3c/webdriver-bidi`.
        default: w3c/webdriver-bidi
        required: false
        type: string

jobs:
  build:
    name: Build WebDriverBidi types
    runs-on: ubuntu-latest
    steps:
      - name: Check out the main spec repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: ${{ github.event.inputs.repository || 'w3c/webdriver-bidi' }}
          ref: ${{ github.event.inputs.source_ref || 'main' }}
          path: webdriver-bidi
      - name: Check out w3c/permissions spec repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: w3c/permissions
          ref: main
          path: permissions
      - name: Generate WebDriverBidi CDDL
        run: ./scripts/test.sh
        working-directory: webdriver-bidi
      - name: Upload WebDriverBidi CDDL
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          name: all-cddl
          path: webdriver-bidi/all.cddl
      - name: Generate WebDriverBidi CDDL for Permissions
        run: ../webdriver-bidi/scripts/cddl/generate.js ./index.html && mv all.cddl permissions.cddl
        working-directory: permissions
      - name: Upload WebDriverBidi CDDL for Permissions
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          name: permissions-cddl
          path: permissions/permissions.cddl

  pr:
    name: Send PR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out mapper repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.11'
          cache: pip
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.0
        with:
          go-version: '1.21.x'
      - name: Install cddlconv
        run: cargo install cddlconv@0.1.5
      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - uses: google/wireit@83d7f8bed70b7bcfc40f4b9f54f4b7485753991b # setup-github-actions-caching/v2.0.1
      - name: Install and build npm dependencies
        run: npm ci
      - name: Download WebDriverBidi CDDL
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: all-cddl
      - name: Download WebDriverBidi CDDL for Permissions
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: permissions-cddl
      - name: Generate TypeScript types for the main spec
        run: node tools/generate-bidi-types.mjs --cddl-file all.cddl
      - name: Generate TypeScript types for Permissions spec
        run: node tools/generate-bidi-types.mjs --cddl-file permissions.cddl --ts-file src/protocol/generated/webdriver-bidi-permissions.ts --zod-file src/protocol-parser/generated/webdriver-bidi-permissions.ts
      - run: git diff
      # Needed for `npm run format`.
      - run: python -m pip install pre-commit
      - run: python -m pip freeze --local
      - name: Run formatter
        run: npm run format || npm run format
        continue-on-error: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-bidi-types
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: 'build(spec): update WebDriverBidi types'
          title: 'build(spec): update WebDriverBidi types'
          body: Automatically generated by https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-bidi-types.yml
          push-to-fork: browser-automation-bot/chromium-bidi
