# This workflow will update the WebdriverBidi types.

name: Update WebdriverBidi types

# Declare default permissions as read only.
permissions: read-all

on:
  schedule:
    # Run daily at 10AM.
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      source_ref:
        description: Ref in spec repo to update from. Default is `main`.
        default: main
        required: false
        type: string
      repository:
        description: Repository with the spec to update from. Default is `w3c/webdriver-bidi`.
        default: w3c/webdriver-bidi
        required: false
        type: string

jobs:
  build:
    name: Build WebDriverBidi types
    runs-on: ubuntu-latest
    steps:
      - name: Check out spec repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5.3
        with:
          repository: ${{ github.event.inputs.repository || 'w3c/webdriver-bidi' }}
          ref: ${{ github.event.inputs.source_ref || 'main' }}
      - name: Generate WebDriverBidi CDDL
        run: ./scripts/test.sh
      - name: Upload WebDriverBidi CDDL
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: all-cddl
          path: all.cddl
  pr:
    name: Send PR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out mapper repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5.3
      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11'
          cache: pip
      - name: Install cddlconv
        run: cargo install cddlconv@0.1.2
      - name: Set up Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          cache: npm
      - uses: google/wireit@f3a3c79c553122e2fe5829eeac7d815326502903 # setup-github-actions-caching/v1
      - name: Install and build npm dependencies
        run: npm ci
      - name: Download WebDriverBidi CDDL
        uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b # v3.0.2
        with:
          name: all-cddl
      - name: Generate TypeScript types
        run: npm run bidi-types -- all.cddl
      # Needed for `npm run format`.
      - name: Install pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 #v3.0.0
      - name: Run formatter
        run: npm run format || exit 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-bidi-types
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: 'build(spec): update WebDriverBidi types'
          title: 'build(spec): update WebDriverBidi types'
          body: Automatically generated by https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-bidi-types.yml
          labels: dependencies
