# This workflow will update the WebdriverBidi types.

name: Update WebdriverBidi types

# Declare default permissions as read only.
permissions: read-all

on:
  schedule:
    # Run daily at 10AM.
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      source_ref:
        description: Ref in spec repo to update from. Default is `main`.
        default: main
        required: false
        type: string
      repository:
        description: Repository with the spec to update from. Default is `w3c/webdriver-bidi`.
        default: w3c/webdriver-bidi
        required: false
        type: string

jobs:
  build:
    name: Build WebDriverBidi types
    runs-on: ubuntu-latest
    steps:
      - name: Check out the main spec repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.event.inputs.repository || 'w3c/webdriver-bidi' }}
          ref: ${{ github.event.inputs.source_ref || 'main' }}
          path: webdriver-bidi
      - name: Check out w3c/permissions spec repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: w3c/permissions
          ref: main
          path: permissions
      - name: Generate WebDriverBidi CDDL
        run: ./scripts/test.sh
        working-directory: webdriver-bidi
      - name: Upload WebDriverBidi CDDL
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: all-cddl
          path: webdriver-bidi/all.cddl
      - name: Generate WebDriverBidi CDDL for Permissions
        run: ../webdriver-bidi/scripts/cddl/generate.js ./index.html && mv all.cddl permissions.cddl
        working-directory: permissions
      - name: Upload WebDriverBidi CDDL for Permissions
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: permissions-cddl
          path: permissions/permissions.cddl

  pr:
    name: Send PR
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out mapper repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11'
          cache: pip
      - name: Install cddlconv
        run: cargo install cddlconv@0.1.2
      - name: Set up Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: lts/*
          cache: npm
      - uses: google/wireit@f3a3c79c553122e2fe5829eeac7d815326502903 # setup-github-actions-caching/v1
      - name: Install and build npm dependencies
        run: npm ci
      - name: Download WebDriverBidi CDDL
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: all-cddl
      - name: Download WebDriverBidi CDDL for Permissions
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: permissions-cddl
      - name: Generate TypeScript types for the main spec
        run: npm run bidi-types -- --cddl-file all.cddl
      - name: Generate TypeScript types for Permissions spec
        run: npm run bidi-types -- --cddl-file permissions.cddl --ts-file src/protocol/generated/webdriver-bidi-permissions.ts --zod-file src/protocol-parser/generated/webdriver-bidi-permissions.ts
      - run: git diff
      # Needed for `npm run format`.
      - run: python -m pip install pre-commit
      - run: python -m pip freeze --local
      - name: Run formatter
        run: npm run format || exit 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          token: ${{ secrets.BROWSER_AUTOMATION_BOT_TOKEN }}
          branch: browser-automation-bot/update-bidi-types
          delete-branch: true
          committer: Browser Automation Bot <browser-automation-bot@google.com>
          author: Browser Automation Bot <browser-automation-bot@google.com>
          commit-message: 'build(spec): update WebDriverBidi types'
          title: 'build(spec): update WebDriverBidi types'
          body: Automatically generated by https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-bidi-types.yml
          labels: dependencies
