# This workflow will check out wpt and run the WebDriver BiDi tests against our
# implementation sharded without generating report or updating expectations.

name: WPT quick

# Declare default permissions as read only.
permissions: read-all

env:
  DEBUG: 'bidi:server:*,bidi:mapper:*'
  DEBUG_DEPTH: 10
  FORCE_COLOR: 3
  PIP_DISABLE_PIP_VERSION_CHECK: 1

on:
  merge_group:
  pull_request:
  workflow_dispatch:
    inputs:
      tests:
        description: Tests to run (e.g. 'network/combined/')
        required: false
        type: string
      verbose:
        description: Verbose logging
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  wpt-required:
    name: '[Required] WPT sink'
    needs: [wpt]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: ${{ needs.wpt.result != 'success' }}
        run: 'exit 1'
      - run: 'exit 0'
  wpt:
    name: ${{ matrix.this_chunk }}/${{ matrix.total_chunks }} ${{ matrix.kind }}-${{ matrix.head }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind: [chromedriver, mapper]
        head: [headless, headful]
        total_chunks: [6]
        this_chunk: [1, 2, 3, 4, 5, 6]
        exclude:
          # Don't run headful mapper, as it takes too long.
          - kind: mapper
            head: headful
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - uses: google/wireit@4aad131006ea85c1e42af927534ebb13426dd730 # setup-github-actions-caching/v1.0.2
      - name: Install and build npm dependencies
        run: npm ci
      - name: Setup dirs
        run: mkdir -p out
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Set up virtualenv
        run: pip install virtualenv
      - name: Set up hosts
        run: ./wpt make-hosts-file | sudo tee -a /etc/hosts
        working-directory: wpt
      - name: Setup cache for browser binaries
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/chromium-bidi
          key: ${{ runner.os }}-browsers-${{ hashFiles('.browser') }}) }}
      - name: Install pinned browser
        id: browser
        run: node tools/install-browser.mjs --github
      - name: Run WPT tests
        timeout-minutes: 60
        run: >
          xvfb-run --auto-servernum
          npm run wpt -- "webdriver/tests/bidi/${{ github.event.inputs.tests }}"
        env:
          BROWSER_BIN: ${{ steps.browser.outputs.executablePath }}
          CHROMEDRIVER: ${{ matrix.kind == 'chromedriver' }}
          HEADLESS: ${{ matrix.head!='headful' }}
          THIS_CHUNK: ${{ matrix.this_chunk }}
          TOTAL_CHUNKS: ${{ matrix.total_chunks }}
          UPDATE_EXPECTATIONS: false
          VERBOSE: ${{ github.event.inputs.verbose }}
          WPT_REPORT: out/wptreport.${{ matrix.kind }}-${{ matrix.head }}-${{ matrix.this_chunk }}.${{ matrix.total_chunks }}.json
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ matrix.kind }}-${{ matrix.head }}-${{ matrix.this_chunk }}.${{ matrix.total_chunks }}-artifacts
          path: |
            logs
            out
