# This workflow will check out wpt and run the WebDriver BiDi tests against our
# implementation.

name: WPT detailed

# Declare default permissions as read only.
permissions: read-all

env:
  DEBUG: 'bidi:server:*,bidi:mapper:*'
  DEBUG_DEPTH: 10
  FORCE_COLOR: 3
  PIP_DISABLE_PIP_VERSION_CHECK: 1

on:
  push:
    branches: 'main'
  workflow_dispatch:
    inputs:
      auto-commit:
        description: Auto-commit expectations
        default: false
        required: false
        type: boolean
      tests:
        description: Tests to run (e.g. 'network/combined/')
        required: false
        type: string
      verbose:
        description: Verbose logging
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  wpt-report:
    name: WPT report
    needs: wpt
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: chromedriver-headful-artifacts
      - name: Prepare Pages
        run: |
          mkdir -p out/site
          cp out/wptreport.json out/site/wptreport.json
          cp out/wptreport.html out/site/index.html
          cp out/wptreport-2023.html out/site/2023.html
      - name: Setup Pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4.0.0
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: out/site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@decdde0ac072f6dcbe43649d82d9c635fff5b4e4 # v4.0.4
  wpt-auto-commit:
    name: WPT auto-commit expectations
    needs: wpt
    if: ${{ !cancelled() && github.event.inputs.auto-commit == 'true' }}
    runs-on: ubuntu-latest
    # Give GITHUB_TOKEN write permission to commit and push.
    # Needed by stefanzweifel/git-auto-commit-action.
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: rm -rf wpt-metadata/chromedriver/headless/*
      - run: rm -rf wpt-metadata/chromedriver/headful/*
      - run: rm -rf wpt-metadata/mapper/headless/*
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: chromedriver-headless-wpt-metadata
          path: wpt-metadata/chromedriver/headless
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: chromedriver-headful-wpt-metadata
          path: wpt-metadata/chromedriver/headful
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: mapper-headless-wpt-metadata
          path: wpt-metadata/mapper/headless
      - name: Auto-commit WPT expectations
        if: (success() || failure()) && github.event.inputs.auto-commit == 'true'
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
        with:
          commit_message: Update WPT expectations
          commit_options: -n --signoff
          file_pattern: 'wpt-metadata/**/*.ini'
  wpt:
    name: ${{ matrix.kind }}-${{ matrix.head }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind: [chromedriver, mapper]
        head: [headful, headless]
        exclude:
          # Don't run headful mapper, as it takes too long.
          - kind: mapper
            head: headful
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - uses: google/wireit@4aad131006ea85c1e42af927534ebb13426dd730 # setup-github-actions-caching/v1.0.2
      - name: Install and build npm dependencies
        run: npm ci
      - name: Setup dirs
        run: mkdir -p out
      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Set up virtualenv
        run: pip install virtualenv
      - name: Set up hosts
        run: ./wpt make-hosts-file | sudo tee -a /etc/hosts
        working-directory: wpt
      - name: Setup cache for browser binaries
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
        with:
          path: ~/.cache/chromium-bidi
          key: ${{ runner.os }}-browsers-${{ hashFiles('.browser') }}) }}
      - name: Install pinned browser
        id: browser
        run: node tools/install-browser.mjs --github
      - name: Run WPT tests (${{matrix.kind}}, ${{matrix.head}})
        timeout-minutes: 60
        run: >
          xvfb-run --auto-servernum
          npm run wpt -- "webdriver/tests/bidi/${{ github.event.inputs.tests }}"
        env:
          BROWSER_BIN: ${{ steps.browser.outputs.executablePath }}
          CHROMEDRIVER: ${{matrix.kind == 'chromedriver'}}
          HEADLESS: ${{matrix.head=='headless'}}
          UPDATE_EXPECTATIONS: true
          VERBOSE: ${{ github.event.inputs.verbose }}
          WPT_REPORT: out/wptreport.json
      - name: Generate HTML test report
        if: success() || failure()
        run: >
          node tools/wpt-report-builder/builder.mjs
          out/wptreport.json
          out/wptreport.html
          out/wptreport-2023.html
      - name: Upload expectations
        if: success() || failure()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: ${{ matrix.kind }}-${{ matrix.head }}-wpt-metadata
          path: wpt-metadata/${{ matrix.kind }}/${{ matrix.head }}
      - name: Upload artifacts
        if: success() || failure()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: ${{ matrix.kind }}-${{ matrix.head }}-artifacts
          path: |
            logs
            out
