# This workflow will check out wpt and run the WebDriver BiDi tests against our
# implementation.

name: web-platform-tests

on:
  pull_request:
    branches: '*'

jobs:
  wpt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      # WPT setup
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Set up virtualenv
        run: pip install virtualenv
      - uses: actions/checkout@v2
        with:
          repository: web-platform-tests/wpt
          path: wpt
          fetch-depth: 1
      - name: Set up hosts
        run: ./wpt make-hosts-file | sudo tee -a /etc/hosts
        working-directory: wpt
      # TODO: install certs
      - name: Install Chrome
        run: ./wpt install chrome browser
        working-directory: wpt
      - name: Run tests
        # For verbose debug logging, add --log-mach - --log-mach-level info
        run: ./wpt run --webdriver-binary=../runBiDiServer.sh --binary _venv3/browsers/nightly/chrome-linux/chrome --log-wptreport=wptreport.json chrome webdriver/tests/bidi/session_subscribe/
        working-directory: wpt
      - name: Update expectations
        if: ${{ failure() }}
        run: |
          mkdir ../metadata
          ./wpt update-expectations --product chrome --metadata ../metadata wptreport.json
          find ../metadata
        working-directory: wpt
      - name: Show log on failure
        if: ${{ failure() }}
        # Note: runBiDiServer.sh will be run multiple times and log.txt will be
        # overwritten. The problem might not be in the log.txt written last.
        run: cat log.txt
env:
  FORCE_COLOR: 3
