# This workflow will check out wpt and run the WebDriver BiDi tests against our
# implementation.

name: Web platform tests with ChromeDriver

on:
  pull_request:
  push:
    branches: 'main'

jobs:
  wpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install and build npm dependencies
        run: npm ci
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Set up virtualenv
        run: pip install virtualenv
      - name: Set up hosts
        run: ./wpt make-hosts-file | sudo tee -a /etc/hosts
        working-directory: wpt
      # TODO: Install a pinned version of Chromium. This may become possible
      # after https://github.com/web-platform-tests/wpt/issues/28970.
      - name: Install Chromium
        # This installs dev chrome to `/usr/bin/google-chrome-unstable`.
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-unstable
      - name: Run tests
        run: >
          ./wpt run 
          --binary-arg="--headless=new" 
          --webdriver-arg="bidi-mapper-path=../lib/iife/mapperTab.js"  
          --webdriver-arg="--log-path=../log/chromeDriver.log" 
          --webdriver-arg="--verbose" 
          --install-webdriver --channel=dev --yes
          --manifest MANIFEST.json 
          --metadata ../wpt-metadata/chromeDriver  
          --log-wptreport wptreport.json 
          chrome 
          webdriver/tests/bidi/session/status/status.py
        working-directory: wpt
      - name: Update expectations
        if: ${{ always() }}
        run: ./wpt update-expectations --product chromium --manifest MANIFEST.json --metadata ../wpt-metadata/chromeDriver wptreport.json
        working-directory: wpt
      - name: Upload expectations
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: wpt-metadata-chromeDriver
          path: wpt-metadata/chromeDriver
      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: logs
          # Note: runBiDiServer.sh will be run multiple times and log.txt will be
          # overwritten. The problem might not be in the log.txt written last.
          path: logs
env:
  FORCE_COLOR: 3
